# Generated by Django 5.1 on 2024-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortinghat', '0003_remove_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
