# Generated by Django 5.1 on 2024-09-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_link_name_alter_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='uuid',
        ),
    ]
