# Generated by Django 5.1 on 2024-09-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_rename_link_link_uuid'),
        ('sortinghat', '0003_remove_name_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.link')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sortinghat.name')),
            ],
        ),
    ]
